# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "test@email.com", password: "password")
User.create(email: "user@email.com", password: "password")

Ingredient.create(name: "High Fructose Corn Syrup", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Turbinado Sugar", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Modified Corn Starch", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Sugar", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Invert Sugar", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Corn Syurp", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Tartaric Acid", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Citric Acid", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Natural and Artificial Favors", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Yellow 6", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Red 40", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Yellow 5", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Blue 1", is_vegetarian: "yes", is_vegan: "yes")
Ingredient.create(name: "Albumen", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Bone Char", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Butter Fat", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Casein", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Sodium Caseinate", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Lactose", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Whey Powder", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Caseinate", is_vegetarian: "yes", is_vegan: "no")
Ingredient.create(name: "Gelatin", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Lard", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "L-cysteine", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Monoglyceride", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Diglyceride", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Shellac", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Vitamin D3", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Cochineal", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Carmine", is_vegetarian: "no", is_vegan: "no")
Ingredient.create(name: "Honey", is_vegetarian: "yes", is_vegan: "no")

Edible.create(name: "Top Ramen Soy Flavor", upc: "038678561125", user_id: "2")
Edible.create(name: "Sour Patch Kids", upc: "038678561126", user_id: "2")
Edible.create(name: "Pemmican Peppered Beef Jerky", upc: "038678561127", user_id: "2")
Edible.create(name: "Sour Punch Straws", upc: "038678561128", user_id: "2")
Edible.create(name: "Updated fake food", upc: "038678561130", user_id: "2")

FoodLabel.create(edible_id: 2, ingredient_id: 4)
FoodLabel.create(edible_id: 2, ingredient_id: 5)
FoodLabel.create(edible_id: 2, ingredient_id: 6)
FoodLabel.create(edible_id: 2, ingredient_id: 7)
FoodLabel.create(edible_id: 2, ingredient_id: 8)
FoodLabel.create(edible_id: 2, ingredient_id: 9)
FoodLabel.create(edible_id: 2, ingredient_id: 10)
FoodLabel.create(edible_id: 2, ingredient_id: 11)
FoodLabel.create(edible_id: 2, ingredient_id: 12)
FoodLabel.create(edible_id: 2, ingredient_id: 13)
