# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "test@email.com", password: "password")
User.create(email: "user@email.com", password: "password")
User.create(email: "demo@email.com", password: "password")

Ingredient.create(name: "High Fructose Corn Syrup", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Turbinado Sugar", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Modified Corn Starch", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Sugar", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Invert Sugar", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Corn Syurp", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tartaric Acid", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Citric Acid", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Natural and Artificial Favors", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Yellow 6", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Red 40", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Yellow 5", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Blue 1", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Albumen", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Bone Char", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Butter Fat", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Casein", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Sodium Caseinate", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Lactose", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Whey Powder", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Caseinate", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Gelatin", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Lard", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "L-cysteine", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Monoglyceride", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Diglyceride", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Shellac", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Vitamin D3", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Cochineal", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Carmine", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Honey", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Bee Pollen", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Barley", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Oats", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Rice", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Quinoa", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Millet", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tofu", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tempeh", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "TVP", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Seitan", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Peanut", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Almond", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Walnut", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Cashew", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tahini", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Flax Seeds", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Chia Seeds", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Olive Oil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Canola Oil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Coconut Oil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Balsamic vinegar", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Rice Wine", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Apple Cider", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "White distilled vinegar", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Basil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Chives", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Oregano", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Thyme", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Sage", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Rosemary", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Bay Leaf", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Cilantro", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Italian Parsley", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Lemongrass", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Black Pepper", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Garlic Powder", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Onion Powder", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Mustard Seed", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Nutmeg", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Clove", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Cinnamon", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Allspice", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Paprika", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Chili Powder", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Turmeric", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Curry Powder", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Ginger", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Nutritional Yeast", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Dried Mushrooms", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Liquid Smoke", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Soy Sauce", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tamari Sauce", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Miso", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Arame", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Wakame", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Dulse", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Nori", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Dried Seaweed", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Mustard", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Flour", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Baking Soda", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Baking Powder", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Dried Fruits", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Rennet", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Ambergris", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Castor oil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Carminic Acid", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Castor", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Castoreum", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Isinglass", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Milk protein concentrate", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Milk protein", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Wheat Flour", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Malic Acid", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Maltodextrin", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Dextrose", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Modified Food Starch (Corn)", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Palm Oil", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Water", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Lemon Juice from Concentrate", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Confectioner's Glaze (Shellac)", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Natural and Artificial Flavor", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Acacia (Gum Arabic)", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Carnauba Wax", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "White Mineral Oil", is_vegetarian: true, is_vegan: true)

Edible.create(name: "Sour Patch Kids", upc: "038678561126", user_id: 3)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579719816/xijjv1kjvd857xyoawnu.jpg", edible_id: 1)
FoodLabel.create(edible_id: 1, ingredient_id: 4)
FoodLabel.create(edible_id: 1, ingredient_id: 5)
FoodLabel.create(edible_id: 1, ingredient_id: 6)
FoodLabel.create(edible_id: 1, ingredient_id: 7)
FoodLabel.create(edible_id: 1, ingredient_id: 8)
FoodLabel.create(edible_id: 1, ingredient_id: 9)
FoodLabel.create(edible_id: 1, ingredient_id: 10)
FoodLabel.create(edible_id: 1, ingredient_id: 11)
FoodLabel.create(edible_id: 1, ingredient_id: 12)
FoodLabel.create(edible_id: 1, ingredient_id: 13)

Edible.create(name: "Mini Airheads", upc: "038000138601", user_id: 3)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579719820/yybp2jamlsxggt1cy3zy.png", edible_id: 2)
FoodLabel.create(edible_id: 2, ingredient_id: 4)
FoodLabel.create(edible_id: 2, ingredient_id: 1)
FoodLabel.create(edible_id: 2, ingredient_id: 106)
FoodLabel.create(edible_id: 2, ingredient_id: 107)
FoodLabel.create(edible_id: 2, ingredient_id: 108)
FoodLabel.create(edible_id: 2, ingredient_id: 109)
FoodLabel.create(edible_id: 2, ingredient_id: 110)
FoodLabel.create(edible_id: 2, ingredient_id: 8)
FoodLabel.create(edible_id: 2, ingredient_id: 10)
FoodLabel.create(edible_id: 2, ingredient_id: 11)
FoodLabel.create(edible_id: 2, ingredient_id: 12)
FoodLabel.create(edible_id: 2, ingredient_id: 13)

Edible.create(name: "Lemonheads", upc: "038000138603", user_id: 3)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579720073/aqg5d04xmukgb6bevhpf.png", edible_id: 3)
FoodLabel.create(edible_id: 3, ingredient_id: 4)
FoodLabel.create(edible_id: 3, ingredient_id: 6)
FoodLabel.create(edible_id: 3, ingredient_id: 8)
FoodLabel.create(edible_id: 3, ingredient_id: 111)
FoodLabel.create(edible_id: 3, ingredient_id: 112)
FoodLabel.create(edible_id: 3, ingredient_id: 113)
FoodLabel.create(edible_id: 3, ingredient_id: 114)
FoodLabel.create(edible_id: 3, ingredient_id: 108)
FoodLabel.create(edible_id: 3, ingredient_id: 115)
FoodLabel.create(edible_id: 3, ingredient_id: 12)
FoodLabel.create(edible_id: 3, ingredient_id: 116)

Edible.create(name: "Twizzlers", upc: "038000138605", user_id: 3)

Edible.create(name: "Smarties", upc: "038000138607", user_id: 3)

Edible.create(name: "Swedish Fish", upc: "038000138611", user_id: 3)

Edible.create(name: "Skittles", upc: "038000138621", user_id: 3)

Edible.create(name: "Sweet Tarts", upc: "038000138634", user_id: 3)

Edible.create(name: "Trolli Sour Brite Crawlers", upc: "038000138577", user_id: 3)

Edible.create(name: "Top Ramen Soy Flavor", upc: "038678561125", user_id: 3)

Edible.create(name: "Zotz", upc: "038678561126", user_id: 3)

Edible.create(name: "Sour Punch Straws", upc: "038678561127", user_id: 3)

LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/tia95kfahpenwo5rf02t.jpg", edible_id: 3)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/xiqrrhn2ahklbyujtviq.png", edible_id: 4)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/jxtkwx4zvs9vxabssce9.jpg", edible_id: 11)
