# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "test@email.com", password: "password")
User.create(email: "user@email.com", password: "password")
User.create(email: "demo@email.com", password: "password")

Ingredient.create(name: "High Fructose Corn Syrup", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Turbinado Sugar", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Modified Corn Starch", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Sugar", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Invert Sugar", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Corn Syurp", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Tartaric Acid", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Citric Acid", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Natural and Artificial Favors", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Yellow 6", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Red 40", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Yellow 5", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Blue 1", is_vegetarian: true, is_vegan: true)
Ingredient.create(name: "Albumen", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Bone Char", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Butter Fat", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Casein", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Sodium Caseinate", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Lactose", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Whey Powder", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Caseinate", is_vegetarian: true, is_vegan: false)
Ingredient.create(name: "Gelatin", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Lard", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "L-cysteine", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Monoglyceride", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Diglyceride", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Shellac", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Vitamin D3", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Cochineal", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Carmine", is_vegetarian: false, is_vegan: false)
Ingredient.create(name: "Honey", is_vegetarian: true, is_vegan: false)

Edible.create(name: "Top Ramen Soy Flavor", upc: "038678561125", user_id: 3)
Edible.create(name: "Sour Patch Kids", upc: "038678561126", user_id: 3)
Edible.create(name: "Sour Punch Straws", upc: "038678561127", user_id: 3)
Edible.create(name: "Trolli Sour Brite Crawlers", upc: "038000138577", user_id: 3)

FoodLabel.create(edible_id: 2, ingredient_id: 4)
FoodLabel.create(edible_id: 2, ingredient_id: 5)
FoodLabel.create(edible_id: 2, ingredient_id: 6)
FoodLabel.create(edible_id: 2, ingredient_id: 7)
FoodLabel.create(edible_id: 2, ingredient_id: 8)
FoodLabel.create(edible_id: 2, ingredient_id: 9)
FoodLabel.create(edible_id: 2, ingredient_id: 10)
FoodLabel.create(edible_id: 2, ingredient_id: 11)
FoodLabel.create(edible_id: 2, ingredient_id: 12)
FoodLabel.create(edible_id: 2, ingredient_id: 13)

LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/iz8op9se6py9ppxypqqd.png", edible_id: 1)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/jxtkwx4zvs9vxabssce9.jpg", edible_id: 2)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/tia95kfahpenwo5rf02t.jpg", edible_id: 3)
LabelImage.create(url: "https://res.cloudinary.com/neah-dev/image/upload/v1579469493/xiqrrhn2ahklbyujtviq.png", edible_id: 4)
